spring:
  application:
    name: basic-secure-service1

server:
  port: ${PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

authentication:
  clients:
    - username: rw
      password: rw
      roles: READ,WRITE
    - username: r
      password: r
      roles: READ
    - username: w
      password: w
      roles: WRITE
