spring:
  application:
    name: cert-secure-service1
  security:
    user:
      name: Admin
      password: admin

server:
  port: ${PORT:8084}
  ssl:
    keyStore: ./ca/localhost.p12
    keyStorePassword: ${PASSWORD}
    keyAlias: localhost
    keyPassword: ${PASSWORD}
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
