spring:
  application:
    name: secure-cert-client1

server:
  port: ${PORT:8085}
  ssl:
    protocol: TLS
    enabled: true
    clientAuth: need
    keyStore: classpath:secure-cert-client1.p12
    keyStorePassword: ${PASSWORD}
    keyAlias: secure-cert-client1
    keyPassword: ${PASSWORD}
    trustStore: classpath:secure-cert-client1.p12
    trustStorePassword: ${PASSWORD}
    trustPassword: ${PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
