spring:
  application:
    name: spring-cloud-registry

server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  renewalPercentThreshold: 0.85
