spring:
  application:
    name: secure-cert-registry
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

server:
  port: ${PORT:8762}
  ssl:
    protocol: TLS
    enabled: true
    clientAuth: need
    oneWayAuthenticationEnabled: false
    twoWayAuthenticationEnabled: true
    keyStore: classpath:secure-cert-registry.p12
    keyStorePassword: ${PASSWORD}
    keyAlias: secure-cert-registry
    keyPassword: ${PASSWORD}
    trustStore: classpath:secure-cert-registry.p12
    trustStorePassword: ${PASSWORD}
    trustPassword: ${PASSWORD}

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    securePortEnabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
  renewalPercentThreshold: 0.85
